name: Bug report
description: Create a report to help improve this project.
title: "[BUG]"
labels:
  - bug
assignees:
  - eliashaeussler
body:
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What Browser are you using?
      placeholder: 'e.g. Chrome 96.0.4664.110'
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: What operating system are you using?
      placeholder: 'e.g. macOS 11.4'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: A clear and concise description of what the bug is.
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: If possible, describe steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: markdown
    attributes:
      value: >
        :bulb: **Tip:** Have you already looked into our
        [Slack channel](https://typo3.slack.com/archives/C037V1Z1SFK)? Maybe your problem has
        already been discussed there.
