services:
  # Disable logger to avoid showing errors during tests
  logger: '@Psr\Log\NullLogger'

  App\Service\ApiService:
    public: true

  App\Cache\RandomExtensionMetadataCacheWarmer: ~

  App\Controller\HealthController:
    autoconfigure: true
    arguments:
      $healthChecks: ['@test.health_check']

  test.health_check:
    class: 'App\Tests\Fixtures\DummyHealthCheck'
