name: Dependabot auto-merge
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.2.0
        with:
          target: minor
          approve-only: true
