name: Dependabot auto-merge
on:
  pull_request:

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.MERGE_TOKEN }}
