name: CGL
on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:
    branches:
      - '**'
      - '!renovate/**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2, composer-require-checker, composer-unused:0.7
          coverage: none
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      # Validation
      - name: Validate composer.json
        run: composer validate

      # Install dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Install node modules
        run: yarn --frozen-lockfile

      # Audit packages
      - name: Audit Composer dependencies
        run: composer audit
      - name: Audit Frontend dependencies
        run: yarn audit

      # Check dependencies
      - name: Check dependencies
        run: composer-require-checker check
      - name: Check for unused Composer dependencies
        run: composer-unused --excludePackage=symfony/css-selector
      - name: Check for unused Frontend dependencies
        run: yarn check-dependencies

      # Linting
      - name: Lint composer.json
        run: composer lint:composer
      - name: Lint PHP
        run: composer lint:php
      - name: Lint CSS
        run: yarn lint:css
      - name: Lint JavaScript
        run: yarn lint:js

      # SCA
      - name: SCA PHP
        run: composer sca -- --error-format github

      # Migration
      - name: Rector migration
        run: composer migration -- --dry-run
