name: CGL
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  cgl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2

      # Install dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress
      - name: Install node modules
        run: yarn --frozen-lockfile

      # Linting
      - name: Lint composer.json
        run: composer normalize --dry-run
      - name: Lint PHP
        run: composer lint -- --dry-run
      - name: Lint CSS
        run: yarn lint:css
      - name: Lint JavaScript
        run: yarn lint:js

      # SCA
      - name: SCA PHP
        run: composer sca -- --error-format github

      # Requirements
      - name: Check Composer requirements
        run: |
          composer global require maglnet/composer-require-checker:"^4.0"
          composer-require-checker check
