name: Dependabot
on:
  push:
    branches:
      - 'dependabot/**'
  pull_request:
    branches:
      - 'dependabot/**'

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-update:
    if: ${{ github.actor == 'dependabot[bot]' && startsWith(github.ref, 'refs/heads/dependabot/composer/') }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2

      # Normalize composer.json
      - name: Install Composer dependencies
        run: composer install --no-progress
      - name: Normalize composer.json
        run: composer normalize --no-check-lock

      # Update PR
      - name: Get last commit message
        id: last-commit-message
        run: |
          echo "::set-output name=msg::$(git log -1 --pretty=%s)"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true

  dependabot-auto-merge:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
