name: Dependabot update
on:
  push:
    branches:
      - 'dependabot/composer/**'
  pull_request:
    branches:
      - 'dependabot/composer/**'

jobs:
  dependabot-update:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      # Normalize composer.json
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
      - name: Normalize composer.json
        run: composer normalize --no-check-lock

      # Update PR
      - name: Get last commit message
        id: last-commit-message
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true
