name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    name: 'Create release'

    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    permissions:
      contents: write

    uses: eliashaeussler/gha/.github/workflows/github-release.yaml@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

  deploy-prod:
    name: 'Deploy to production'
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.ref, 'refs/tags/') }}

    environment:
      name: production
      url: https://typo3-badges.dev

    concurrency:
      group: prod
      cancel-in-progress: true

    permissions:
      contents: read

    env:
      APP_ENV: prod

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
        with:
          php-version: 8.5

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
        with:
          composer-options: '--no-dev --optimize-autoloader'

      - name: 'Build assets'
        uses: eliashaeussler/gha/.github/actions/build-assets@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

      - name: 'Deploy'
        uses: eliashaeussler/gha/.github/actions/deploy-app@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          deployer-version: '8.0.5'

  deploy-dev:
    name: 'Deploy to development'
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'workflow_dispatch' }}

    environment:
      name: production
      url: https://pre.typo3-badges.dev

    concurrency:
      group: dev
      cancel-in-progress: true

    permissions:
      contents: read

    env:
      APP_ENV: dev

    steps:
      - name: 'Checkout'
        uses: eliashaeussler/gha/.github/actions/checkout@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

      - name: 'Setup PHP'
        uses: eliashaeussler/gha/.github/actions/setup-php@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
        with:
          php-version: 8.5

      - name: 'Install Composer packages'
        uses: eliashaeussler/gha/.github/actions/composer-install@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
        with:
          composer-options: '--no-dev --optimize-autoloader'

      - name: 'Build assets'
        uses: eliashaeussler/gha/.github/actions/build-assets@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1

      - name: 'Deploy'
        uses: eliashaeussler/gha/.github/actions/deploy-app@24c8e1aa6eb95107a2f97721f962cc6372ae9016 # 0.8.1
        with:
          command: dev
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          deployer-version: '8.0.5'
