name: API schema
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare workflow
    uses: eliashaeussler/.github/.github/workflows/pull-request.yaml@5a6d08a067e0528f2b3d66aa168ffdcff8de68f9 # main

  validate:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue == 'true'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Validate OpenAPI definition
        uses: swaggerexpert/apidom-validate@f839307deab4db59c7814834a2076d309e23b535 # v1.4.1
        with:
          definition-file: spec/typo3-badges.oas3.yaml
          fails-on: 2
